name: Delete Closed Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  delete-closed-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Delete closed issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Get closed issues
            const closedIssues = await github.paginate(github.rest.issues.listForRepo, {
              owner,
              repo,
              state: 'closed',
              per_page: 100
            });
            
            // Optional: Filter issues by age or other criteria
            // For example, only delete issues closed more than 30 days ago
            const thirtyDaysAgo = new Date();
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
            
            const issuesToDelete = closedIssues.filter(issue => {
              const closedAt = new Date(issue.closed_at);
              return closedAt < thirtyDaysAgo;
            });
            
            // Delete filtered issues
            for (const issue of issuesToDelete) {
              console.log(`Deleting issue #${issue.number}: ${issue.title}`);
              await github.rest.issues.delete({
                owner,
                repo,
                issue_number: issue.number
              });
            }
            
            console.log(`Deleted ${issuesToDelete.length} closed issues`);
