name: Cleanup Old Artifacts

on:
  schedule:
    - cron: "0 0 */2 * *" # Runs every 2 days at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: List and delete old artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const twoWeeksAgo = new Date();
            twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 14);

            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const artifact of artifacts.data.artifacts) {
              const createdAt = new Date(artifact.created_at);
              if (createdAt < twoWeeksAgo) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              }
            }
              