name: Delete Closed Issues

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  delete-closed-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Delete closed issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Get all closed issues
            const closedIssues = await github.paginate(github.rest.issues.listForRepo, {
              owner,
              repo,
              state: 'closed',
              per_page: 100
            });
            
            console.log(`Found ${closedIssues.length} closed issues to delete`);
            
            // Delete each closed issue
            for (const issue of closedIssues) {
              try {
                await github.rest.issues.delete({
                  owner,
                  repo,
                  issue_number: issue.number
                });
                console.log(`Deleted issue #${issue.number}: ${issue.title}`);
              } catch (error) {
                console.error(`Failed to delete issue #${issue.number}: ${error.message}`);
              }
            }
            