name: Deploy to k3s with Helm

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Changed from 'self-hosted' to 'ubuntu-latest'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Setup SSH key for k3s access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.48.162.74 >> ~/.ssh/known_hosts

      - name: Get kubeconfig from VM
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.48.162.74 "sudo cat /etc/rancher/k3s/k3s.yaml" > kubeconfig
          sed -i 's/127.0.0.1/13.48.162.74/g' kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-app ./helm-chart \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/learn_git_actions \
            --set image.tag=latest \
            --namespace default \
            --wait --timeout 5m
