name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Run Flask Server on GitHub Runner"]  # The name of your test workflow file
    types:
      - completed  # Triggers when the test workflow finishes

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Runs only if the test workflow succeeded

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the latest code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for multi-platform builds

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store your Docker Hub username in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store your Docker Hub password in GitHub secrets

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest

      - name: Run Trivy scan
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest
          trivy image --format json --output trivy-results.json ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: trivy-scan-results
          path: trivy-results.json
