name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Run Flask Server on GitHub Runner"]
    types:
      - completed

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest .
          docker run --rm aquasec/trivy:latest image --ignore-unfixed --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest || true

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: '${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest'
      #     ignore-unfixed: true
      #     severity: 'HIGH,CRITICAL'
      #   continue-on-error: true  # Allow workflow to continue even if vulnerabilities are found

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Hello @${{ github.actor }}, the Docker build and Trivy scan have completed.",
            "attachments": [
              {
                "color": "#36a64f",
                "title": "Workflow Details",
                "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "Repository: ${{ github.repository }}\nCommit: ${{ github.sha }}\nTriggered by: ${{ github.actor }}"
              }
            ]
          }' $SLACK_WEBHOOK_URL
