name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Run Flask Server on GitHub Runner"]
    types:
      - completed

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF files to the Security tab

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy vulnerability scanner
        run: |
          trivy image --ignore-unfixed --severity HIGH,CRITICAL --format sarif --output trivy-results.sarif ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest
        continue-on-error: true

      - name: Save Trivy Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:latest

      - name: Compress and encode SARIF file
        run: |
          gzip -c trivy-results.sarif > trivy-results.sarif.gz
          base64 trivy-results.sarif.gz > trivy-results.sarif.gz.b64
      
      # - name: Upload SARIF file to GitHub Code Scanning
      #   if: always()
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     SARIF_CONTENT=$(cat trivy-results.sarif.gz.b64)
      #     gh api --method POST /repos/${{ github.repository }}/code-scanning/sarifs \
      #       --field sarif="$SARIF_CONTENT" \
      #       --field commit_sha=${{ github.event.workflow_run.head_commit.id }} \
      #       --field ref=${{ github.ref }}

      - name: Upload SARIF file to GitHub Code Scanning
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SARIF_CONTENT=$(base64 -w 0 trivy-results.sarif)
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/sarifs" \
            -d '{
              "commit_sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}",
              "sarif": "'"${SARIF_CONTENT}"'"
            }'

  # upload-trivy-results:
    # needs: docker-build-push
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v2

    #   - name: Download Trivy Results Artifact
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: trivy-results

    #   - name: Upload Trivy results to Security tab
    #     uses: github/codeql-action/upload-sarif@v3
    #     with:
    #       sarif_file: trivy-result.sarif
