name: CI Docker Build & Push

on:
  push:
    branches: [ "main" ] # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches: [ "main" ] # Trigger on PR targeting main branch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the latest code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for multi-platform builds

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store your Docker Hub username in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store your Docker Hub password in GitHub secrets

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/learn_git_actions:${{ github.sha }}
