name: Python Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black isort mypy bandit
          pip install -r requirements.txt
          
      - name: Run Black (Code Formatter)
        run: black . --check --diff
        
      - name: Run isort (Import Sorter)
        run: isort . --check --diff
        
      - name: Run Flake8 (Style Guide)
        run: flake8 .
        
      - name: Run Pylint (Code Analysis)
        run: pylint $(git ls-files '*.py')
        
      - name: Run MyPy (Type Checking)
        run: mypy .
        
      - name: Run Bandit (Security Checks)
        run: bandit -r . 