name: Run Flask Server on GitHub Runner

on: [push, pull_request]

jobs:
  run_flask:
    runs-on: ubuntu-latest  # Runs on GitHub's cloud server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch repo files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install Flask

      - name: Run Flask Server
        run: |
          python app.py &  # Start Flask in the background
          sleep 5  # Give Flask some time to start

      - name: Debug  # Added debug step
        run: |
          lsof -i :8080
          cat /var/log/syslog | grep python
          ps aux | grep python
          netstat -tulpn | grep 8080

      - name: Test Flask Server
        run: curl http://127.0.0.1:8080  # Access Flask on port 8080
        